name: Test site for publicly known js vulnerabilies

on:
  push:
    branches: [develop]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilies
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: 'iamkjw77.github.io/portfolio'
